### ISSUE TITLE
Expand on what a full license means

### ISSUE THREAD

**Issue by feridunkadir** [MicrosoftDocs/dynamics365-industry-solutions#11]
[Enter feedback here]

The phrase "A full Dynamics 365 license" doesn't mean anything. Each D365 app has licenses. Probably better to change to "Licenses for the required Dynamics 365 apps".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 576ba477-d823-73a9-a37f-09282d6a3ede
* Version Independent ID: 42353bbe-15e3-408f-61e3-6acb500c9040
* Content: [Known issues and limitations for Microsoft Cloud for Healthcare](https://docs.microsoft.com/en-us/dynamics365/industry/healthcare/known-issues-limitations)
* Content Source: [articles/healthcare/known-issues-limitations.md](https://github.com/MicrosoftDocs/dynamics365-industry-solutions-pr/blob/live/articles/healthcare/known-issues-limitations.md)
* Service: **industry**
* Sub-service: **healthcare**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by miraoms** [comment]
Thank you @feridunkadir! The documentation has been updated.
