### ISSUE TITLE
Purpose of dataverse healthcare APIs

### ISSUE THREAD

**Issue by umar-gh** [MicrosoftDocs/dynamics365-industry-solutions#12]
The purpose of having 'Dataverse healthcare apis' when we already have FHIR apis from Azure Health data services should be elaborated.

The diagram in the [overview ](https://learn.microsoft.com/en-us/dynamics365/industry/healthcare/data-integration-toolkit-overview#azure-health-data-services) page recommends to have data flowing from clinical systems into FHIR server and then into DataVerse.
The content on this [page](https://learn.microsoft.com/en-us/dynamics365/industry/healthcare/dataverse-healthcare-apis-overview), seems to talk about ingesting/reading clinical data directly into Dataverse.

- is it just another capability targeted for customers who do not have FHIR in their ecosystem and use only Dataverse?
- Is it that MS is moving towards baking FHIR functionalities into DV which could eliminate the need of FHIR server altogether?
- anything else?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2bb6503-e602-ede7-ec1e-f4e323bb7bd3
* Version Independent ID: d2bb6503-e602-ede7-ec1e-f4e323bb7bd3
* Content: [Overview of Dataverse Healthcare APIs](https://learn.microsoft.com/en-us/dynamics365/industry/healthcare/dataverse-healthcare-apis-overview)
* Content Source: [articles/healthcare/dataverse-healthcare-apis-overview.md](https://github.com/MicrosoftDocs/dynamics365-industry-solutions-pr/blob/live/articles/healthcare/dataverse-healthcare-apis-overview.md)
* Service: **industry**
* Sub-service: **healthcare**
* GitHub Login: @miraoms
* Microsoft Alias: **mirao**

**Comment by jimbonovak** [comment]
The [Dataverse Healthcare APIs](https://learn.microsoft.com/en-us/dynamics365/industry/healthcare/dataverse-healthcare-apis-overview) are our replacement solution for the FHIR Sync Agent. These APIs allow bidirectional sync of data between Dataverse and the FHIR APIs, such as Azure Health Data Services.  

The Dataverse Healthcare APIs allow Microsoft Cloud for Healthcare customers to ingest data to Dataverse without the need for an intermediary FHIR server. These APIs can be invoked by custom code, or you can use the Azure Logic App that can be deployed via Solution Center. You can review the documentation for more information on this.

The APIs allow for ingest, writeback, and limited retrieve capabilities, and can operate without a FHIR server. But, we are not implementing full FHIR server functionality as defined in the HL7 FHIR specifications.
