### ISSUE TITLE
Incorrect Create Portal instructions

### ISSUE THREAD

**Issue by kateshepard** [MicrosoftDocs/dynamics365-industry-solutions#14]
The section on creating the portal does not have accurate steps; there are no "portal" templates available in Create in Power Apps. I believe this section should reference Power Pages instead of Power Apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88383e9c-4e3b-35af-f6a5-29c3bd247f7b
* Version Independent ID: 49860b9f-c991-5e83-6b7b-31f53e690d45
* Content: [Set up and configure a Patient access portal](https://learn.microsoft.com/en-us/dynamics365/industry/healthcare/configure-portals)
* Content Source: [articles/healthcare/configure-portals.md](https://github.com/MicrosoftDocs/dynamics365-industry-solutions-pr/blob/live/articles/healthcare/configure-portals.md)
* Service: **microsoft-cloud-healthcare**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by miraoms** [comment]
Thanks for the feedback, @kateshepard! The documentation has been updated.
