### ISSUE TITLE
Patient observation chart template unavailable

### ISSUE THREAD

**Issue by adityaarora-velrada** [MicrosoftDocs/dynamics365-industry-solutions#15]
While trying to follow the Post Deployment steps for Device data support for Power BI "Patient observation chart", I am unable to find the template for this report. Not sure where to get it from.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8210eae3-b6ca-36f6-eb46-b6bd7f98d682
* Version Independent ID: 8210eae3-b6ca-36f6-eb46-b6bd7f98d682
* Content: [Configure device data support in care management (preview) - Microsoft Cloud for Healthcare](https://learn.microsoft.com/en-us/dynamics365/industry/healthcare/device-data-support-configure?toc=%2Findustry%2Fhealthcare%2Ftoc.json&bc=%2Findustry%2Fbreadcrumb%2Ftoc.json#configure-patient-observation-chart-using-power-bi)
* Content Source: [articles/healthcare/device-data-support-configure.md](https://github.com/MicrosoftDocs/dynamics365-industry-solutions-pr/blob/live/articles/healthcare/device-data-support-configure.md)
* Service: **microsoft-cloud-healthcare**
* GitHub Login: @miraoms
* Microsoft Alias: **mirao**

**Comment by ndutta-ms** [comment]
@adityaarora-velrada thanks for highlighting this. Please follow the below steps to access the template app-

1. Ensure that the solution is successfully installed in Solution center
2. Go to Deployment manager from the navigation menu on the left side of Solution center landing page
3. Choose the appropriate deployment name you used for installing solution
4. Once it opens, you should see the section "Post-deployment configurations" somewhere in the middle of the page. Click on the link in the Action column for "Patient observation chart". It would redirect you to the template app installation page.

Once installed, please refer to the original configuration document on learn.microsoft.com for the next steps. You can check the same document for the prerequisites and troubleshooting guide.

Hope this clarifies!
