### ISSUE TITLE
How to start a trial?

### ISSUE THREAD

**Issue by popujol** [MicrosoftDocs/dynamics365-industry-solutions#4]
Hello, 
I cannot find the information how to start and deploy the solution as a trial .
Could you please let me know if this is possible?

Thank you very much,

Pierre-Olivier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b628dcca-f0f0-5ce4-8f77-700c6ebbf57d
* Version Independent ID: ad4f61fd-2f9e-54ea-41a5-738d3a2c546c
* Content: [Deploy Microsoft Cloud for Healthcare](https://docs.microsoft.com/en-us/dynamics365/industry/healthcare/deploy)
* Content Source: [articles/healthcare/deploy.md](https://github.com/MicrosoftDocs/dynamics365-industry-solutions-pr/blob/live/articles/healthcare/deploy.md)
* Service: **industry**
* Sub-service: **healthcare**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by andreabichsel** [comment]
Thank you for your question! Trial isn't yet available.
