### ISSUE TITLE
Missing Sync agent installation files - on the installation page

### ISSUE THREAD

**Issue by hari-yarapotina** [MicrosoftDocs/dynamics365-industry-solutions#5]
Need to add a section on how to get installation files for Sync Agent. If we are making it as an OSS we need to provide a link or otherwise need to add a section on how to get them. This can go before the pre-requisites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e36863-84fc-372c-e7f8-58ad67d23664
* Version Independent ID: c8e36863-84fc-372c-e7f8-58ad67d23664
* Content: [Install Azure FHIR Sync Agent](https://review.docs.microsoft.com/en-us/dynamics365/industry/healthcare/sync-agent-installation?branch=rearrange-sync-agent&source=docs)
* Content Source: [articles/healthcare/sync-agent-installation.md](https://github.com/MicrosoftDocs/dynamics365-industry-solutions-pr/blob/rearrange-sync-agent/articles/healthcare/sync-agent-installation.md)
* Service: **industry**
* Sub-service: **healthcare**
* GitHub Login: @miraoms
* Microsoft Alias: **mirao**

**Comment by andreabichsel** [comment]
Thanks, @hari-yarapotina! Just letting you know that I have to close this issue, because this is a public-facing page and we need to keep these discussions internal.  @miraoms will work with you and Madhu to add this section. 

Thanks!
Andrea
