### ISSUE TITLE
Overview Page - suggested changes

### ISSUE THREAD

**Issue by hari-yarapotina** [MicrosoftDocs/dynamics365-industry-solutions#6]
[Enter feedback here]
On the overview page following changes are needed.
1. Need to add a title to the diagram "FHIR Sync Agent - Data flow"
2. Premises and guideline should be moved below the data flow diagram
3. Deploy Azure FHIR Sync agent - Section is redundant (as we are giving an overview on this page, from the left menu user can navigate to deploy/install as the next step)
4. Testing overview must be moved after the FHIR Sync agent FHIR resources list.
5. Samples are at this location, which is a private repository.  https://github.com/microsoft/fhir-cds-agent/tree/main/samples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e36863-84fc-372c-e7f8-58ad67d23664
* Version Independent ID: c8e36863-84fc-372c-e7f8-58ad67d23664
* Content: [Install Azure FHIR Sync Agent](https://review.docs.microsoft.com/en-us/dynamics365/industry/healthcare/sync-agent-installation?branch=rearrange-sync-agent&source=docs)
* Content Source: [articles/healthcare/sync-agent-installation.md](https://github.com/MicrosoftDocs/dynamics365-industry-solutions-pr/blob/rearrange-sync-agent/articles/healthcare/sync-agent-installation.md)
* Service: **industry**
* Sub-service: **healthcare**
* GitHub Login: @miraoms
* Microsoft Alias: **mirao**

**Comment by andreabichsel** [comment]
Thanks, @hari-yarapotina! @miraoms will work on adding this. Have to close for now; it's best to contact us internally for doc changes. :)

Thank you so much for all your help!
