### ISSUE TITLE
Installation Page - Add missing images

### ISSUE THREAD

**Issue by hari-yarapotina** [MicrosoftDocs/dynamics365-industry-solutions#7]
Under the Install Sync Agent section, before the deploy scripts we can add the following as a note.

Note: Before deploying Azure FHIR Sync Agent, please ensure that you have [Contributor rights](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles) in your Azure Subscription, and that [Azure API for FHIR](https://docs.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/overview) and [FHIR-Proxy](https://github.com/microsoft/fhir-proxy) have been installed in the [Azure AD tenant](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-whatis#:~:text=Azure%20tenant,tenant%20represents%20a%20single%20organization.) connected with your Azure subscription. It is crucial that Azure API for FHIR, FHIR-Proxy, and Azure FHIR Sync Agent all share the same [Azure Key Vault](https://docs.microsoft.com/en-us/azure/key-vault/general/basic-concepts#:~:text=Azure%20Key%20Vault%20is%20a,security%20module(HSM)%20pools.). 

For this reason, it is recommended to install Azure FHIR Sync Agent into the same [Resource Group](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal#:~:text=A%20resource%20group%20is%20a,to%20manage%20as%20a%20group.) where the shared Key Vault is deployed (it is common to put Azure API for FHIR, FHIR-Proxy, and Azure FHIR Sync Agent all in the same Resource Group with a mutually shared Key Vault).

1. On the installation page, right below deploysyncagent.bash add the below image.
![image](https://user-images.githubusercontent.com/7587468/164612033-ad030bc6-41da-4a19-9cd0-2ba3be279766.png)
2. Add below image, right below setupsyncagent.bash
![image](https://user-images.githubusercontent.com/7587468/164612173-35efbfbe-e9cf-4c29-ac75-d7028b267d2a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e36863-84fc-372c-e7f8-58ad67d23664
* Version Independent ID: c8e36863-84fc-372c-e7f8-58ad67d23664
* Content: [Install Azure FHIR Sync Agent](https://review.docs.microsoft.com/en-us/dynamics365/industry/healthcare/sync-agent-installation?branch=rearrange-sync-agent&source=docs)
* Content Source: [articles/healthcare/sync-agent-installation.md](https://github.com/MicrosoftDocs/dynamics365-industry-solutions-pr/blob/rearrange-sync-agent/articles/healthcare/sync-agent-installation.md)
* Service: **industry**
* Sub-service: **healthcare**
* GitHub Login: @miraoms
* Microsoft Alias: **mirao**

**Comment by andreabichsel** [comment]
Thanks, @hari-yarapotina! @miraoms will work on adding this. Have to close for now; it's best to contact us internally for doc changes. :)
