### ISSUE TITLE
overall flow is confusing

### ISSUE THREAD

**Issue by jimbonovak** [MicrosoftDocs/dynamics365-industry-solutions#8]
titles would work better if they outlined configuring Sync Agent, not Sync Admin.  Sync Admin contains the tools to deploy and manage Sync Agent

so maybe the structure is overview of FHIR -> Azure FHIR server -> Sync Agent -> Sync Admin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9fe1aff-a44a-60d4-6ccf-59c9e99884c8
* Version Independent ID: 64e0ab7f-72ac-ed69-dc33-bf0c21183d7b
* Content: [Overview of Sync admin for FHIR](https://review.docs.microsoft.com/en-us/dynamics365/industry/healthcare/configure-sync-clinical-data?branch=rearrange-sync-agent)
* Content Source: [articles/healthcare/configure-sync-clinical-data.md](https://github.com/MicrosoftDocs/dynamics365-industry-solutions-pr/blob/rearrange-sync-agent/articles/healthcare/configure-sync-clinical-data.md)
* Service: **industry**
* Sub-service: **healthcare**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-stthomas**

**Comment by andreabichsel** [comment]
Hi Jim, the content was reorganized after you submitted this comment. If it still doesn't work, please work internally with PM and doc team. Thank you!
